# Typus Models Configuration File
#
# Use the README file on the same folder as this file as a reference to
# customize this file to your needs.

Theme:
  fields:
    list: title, link, one_line_description
    form: title, link, icon, one_line_description, short_description, long_description
    show: id, title, link, icon, one_line_description, short_description, long_description, created_at, updated_at
  actions:
    index:
    edit:
  order_by:
  relationships: 
  filters:
  search:
  application: itsaconference
  description:

